spring.application.name=linkup-backend
spring.datasource.url=jdbc:mysql://localhost:3306/linkup
spring.datasource.username=root
spring.datasource.password=123@#@#@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect